" ============================
"
" Author : William Liao
" Date   : 2017.05.01
"
" vimrc setting
"
" ============================

source ~/.vim/plugin_setting.vim
source ~/.vim/personal_vim_aliases.vim
source ~/.vim/personal_vim_mappings.vim

" Font
set guifont=Monospace\ 14

" Add line number
set nu


nmap <F2> :q <CR>

" set paste <--> set nopaste
set pastetoggle=<F4>


" pathogen
execute pathogen#infect()

" Be sure to put these 2 lines after the pathogen plugins
" For syntax highlighting and filetype detection in plugins
syntax on
filetype plugin indent on



