" ============================
"
" Author : William Liao
" Date   : 2017.03.27
"
" vimrc setting
"
" ============================

source ~/.vim/plugin_setting.vim

"Add line number
set nu


" pathogen
execute pathogen#infect()

" Be sure to put these 2 lines after the pathogen plugins
" For syntax highlighting and filetype detection in plugins
syntax on
filetype plugin indent on



